// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA53UqnTHS12XEQLkorX1lFJsSNFW5bRpI',
    appId: '1:155163072201:web:4e265dcec63d564d1c5f18',
    messagingSenderId: '155163072201',
    projectId: 'achha-emart',
    authDomain: 'achha-emart.firebaseapp.com',
    storageBucket: 'achha-emart.firebasestorage.app',
    measurementId: 'G-FEXENL1MND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt0g-_84rgG6C0pxRTSlltY238ntXgyKE',
    appId: '1:155163072201:android:8f9938da14bf7cee1c5f18',
    messagingSenderId: '155163072201',
    projectId: 'achha-emart',
    storageBucket: 'achha-emart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbvqp4SvzZD9HVWLVZjvNO8ZHtAM_hgiU',
    appId: '1:155163072201:ios:8830f03f8f82553c1c5f18',
    messagingSenderId: '155163072201',
    projectId: 'achha-emart',
    storageBucket: 'achha-emart.firebasestorage.app',
    iosBundleId: 'com.achhafoods.achhafoods',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbvqp4SvzZD9HVWLVZjvNO8ZHtAM_hgiU',
    appId: '1:155163072201:ios:8830f03f8f82553c1c5f18',
    messagingSenderId: '155163072201',
    projectId: 'achha-emart',
    storageBucket: 'achha-emart.firebasestorage.app',
    iosBundleId: 'com.achhafoods.achhafoods',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA53UqnTHS12XEQLkorX1lFJsSNFW5bRpI',
    appId: '1:155163072201:web:d8f6d682e23aeeed1c5f18',
    messagingSenderId: '155163072201',
    projectId: 'achha-emart',
    authDomain: 'achha-emart.firebaseapp.com',
    storageBucket: 'achha-emart.firebasestorage.app',
    measurementId: 'G-MQJF8107X9',
  );
}
